# Generated by Django 6.0.1 on 2026-02-03 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumberCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameCar', models.CharField(default='Lexus GX 570', max_length=100)),
                ('nummer_car', models.CharField(default='..KG....', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=100)),
                ('choice_car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='relation_db.numbercar')),
            ],
        ),
    ]
